# Logistic Regression Implementation

In [144]:
from sklearn.datasets import load_iris
import pandas as pd

# iris is a flower related dataset

In [145]:
dataset=load_iris() 

#  dataset here is the object returned by load_iris(), and it acts like a dictionary with attributes.

In [146]:
print(dataset.DESCR)

# dataset.DESCR gives you the dataset’s built-in description text (a long human-readable summary)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [147]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [148]:
dataset.target
# type(dataset.target) # this is an ndArray so we will trans

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [149]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [150]:
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [151]:
df['target']=dataset.target

In [152]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [153]:
df.shape

(150, 5)

In [ ]:
# confusion matrix : 

# For a binary classifier, after predicting on test data you get 4 outcomes:

#                         Predicted: Positive         Predicted: Negative

# Actual: Positive        TP (True Positive)          FN (False Negative)
# Actual: Negative        FP (False Positive)         TN (True Negative)

# TP — You said positive, it was positive. Correct.
# TN — You said negative, it was negative. Correct.
# FP — You said positive, actually negative. Type I error.
# FN — You said negative, actually positive. Type II error.

# The matrix tells you where your model fails, not just whether it fails.

# Ex - [[12  0]
#       [ 0  8]]

# it means : 

# 12 → Model predicted class 0, actual was class 0. Correct.
# 8 → Model predicted class 1, actual was class 1. Correct.
# 0 (top right) → Model predicted class 1, actual was class 0. Wrong. → Zero such mistakes.
# 0 (bottom left) → Model predicted class 0, actual was class 1. Wrong. → Zero such mistakes.

In [154]:
# Binary classification

# df[df['target']==2] # therefore these exists

df_copy=df[df['target']!=2] # we can do this to make the classification binary

df_copy.shape

(100, 5)

In [155]:
df_copy.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

# Independent and dependent features

In [156]:
X=df_copy.iloc[:,:-1] # everything except target column
y=df_copy.iloc[:,-1] # only last column

In [157]:
from sklearn.linear_model import LogisticRegression

In [158]:
classifier=LogisticRegression()

In [159]:
# train-test split

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=20,random_state=42)

In [160]:
classifier.fit(X_train,y_train)

LogisticRegression()

In [161]:
# prediction
y_pred=classifier.predict(X_test)

In [162]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [163]:
y_test

83    1
53    1
70    1
45    0
44    0
39    0
22    0
80    1
10    0
0     0
18    0
30    0
73    1
33    0
90    1
4     0
76    1
77    1
12    0
31    0
Name: target, dtype: int64

In [ ]:
# Accuracy, confusion matrix, and classification report
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Always pass y_true first and y_pred second
print('Accuracy:', accuracy_score(y_test, y_pred))
print('\nConfusion Matrix:\n', confusion_matrix(y_test, y_pred))
print('\nClassification Report:\n', classification_report(y_test, y_pred))

1.0
[[12  0]
 [ 0  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

## Additional Concepts You Should Know (Logistic Regression)

These are important topics often asked in interviews and useful in real projects:

1. Sigmoid function and probability output
2. Decision threshold (not always 0.5)
3. Coefficients, odds, and log-odds interpretation
4. Regularization (`L1`, `L2`, and `C`)
5. ROC-AUC and threshold tuning
6. Important assumptions and practical tips

### 1. Sigmoid Function and Why Logistic Regression Gives Probabilities

Logistic Regression predicts a linear score:

$$
z = w_1x_1 + w_2x_2 + ... + b
$$

Then converts it to probability using sigmoid:

$$
\sigma(z)=\frac{1}{1+e^{-z}}
$$

- Output is always between 0 and 1
- This value is the probability of class 1 (positive class)

In [ ]:
# Plot sigmoid curve for intuition
import numpy as np
import matplotlib.pyplot as plt

z = np.linspace(-10, 10, 200)
sigmoid = 1 / (1 + np.exp(-z))

plt.figure(figsize=(8, 4))
plt.plot(z, sigmoid)
plt.axhline(0.5, color='red', linestyle='--', label='0.5 probability')
plt.title('Sigmoid Function')
plt.xlabel('z (linear score)')
plt.ylabel('Probability')
plt.legend()
plt.grid(alpha=0.3)
plt.show()

### 2. Decision Threshold (Very Important)

By default, prediction rule is:
- if probability >= 0.5, predict class 1
- else predict class 0

But threshold can be changed based on business goal:
- Lower threshold: catches more positives, but may increase false positives
- Higher threshold: fewer false positives, but may miss true positives

So 0.5 is not always the best choice.

In [ ]:
# Try different thresholds and observe confusion matrix changes
from sklearn.metrics import confusion_matrix

proba_class1 = classifier.predict_proba(X_test)[:, 1]

for threshold in [0.3, 0.5, 0.7]:
    y_pred_threshold = (proba_class1 >= threshold).astype(int)
    cm = confusion_matrix(y_test, y_pred_threshold)
    acc = accuracy_score(y_test, y_pred_threshold)
    print(f'\nThreshold = {threshold}')
    print('Accuracy:', round(acc, 4))
    print('Confusion Matrix:\n', cm)

### 3. Coefficients, Log-Odds, and Odds Ratio

Logistic regression models **log-odds**:

$$
\log\left(\frac{p}{1-p}\right)=w_1x_1 + w_2x_2 + ... + b
$$

- A positive coefficient increases probability of class 1
- A negative coefficient decreases probability of class 1
- `exp(coefficient)` gives the **odds ratio** for a 1-unit increase in that feature

In [ ]:
# Coefficient interpretation table
coef_values = classifier.coef_[0]  # binary classification gives one coefficient vector
coef_table = pd.DataFrame({
    'feature': X.columns,
    'coefficient': coef_values,
    'odds_ratio_exp_coef': np.exp(coef_values)
}).sort_values('coefficient', ascending=False)

coef_table

### 4. Regularization (`L1`, `L2`) and `C`

Regularization helps prevent overfitting.

- `L2` (Ridge-like): shrinks coefficients smoothly
- `L1` (Lasso-like): can push some coefficients to zero (feature selection effect)
- `C` is inverse of regularization strength:
  - smaller `C` => stronger regularization
  - larger `C` => weaker regularization

In [ ]:
# Compare regularization settings
from sklearn.linear_model import LogisticRegression

settings = [
    ('l2', 0.1),
    ('l2', 1.0),
    ('l2', 10.0),
    ('l1', 0.1),
    ('l1', 1.0),
    ('l1', 10.0),
]

rows = []
for penalty, C in settings:
    model_temp = LogisticRegression(penalty=penalty, C=C, solver='liblinear', random_state=42)
    model_temp.fit(X_train, y_train)
    pred_temp = model_temp.predict(X_test)
    rows.append({
        'penalty': penalty,
        'C': C,
        'test_accuracy': accuracy_score(y_test, pred_temp)
    })

pd.DataFrame(rows).sort_values('test_accuracy', ascending=False)

### 5. ROC Curve and AUC

ROC-AUC evaluates ranking quality of predicted probabilities across all thresholds.

- ROC curve: True Positive Rate vs False Positive Rate
- AUC close to 1: strong separability
- AUC around 0.5: near-random model

This is useful when accuracy alone is not enough.

In [ ]:
# ROC curve and AUC score
from sklearn.metrics import roc_curve, roc_auc_score

fpr, tpr, _ = roc_curve(y_test, proba_class1)
auc_score = roc_auc_score(y_test, proba_class1)

plt.figure(figsize=(6, 5))
plt.plot(fpr, tpr, label=f'ROC curve (AUC = {auc_score:.3f})')
plt.plot([0, 1], [0, 1], linestyle='--', color='gray', label='Random baseline')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend()
plt.grid(alpha=0.3)
plt.show()

### 6. Assumptions and Practical Tips

Logistic Regression works best when:
- Relationship between features and log-odds is approximately linear
- Features are scaled (important for regularized logistic regression)
- Severe multicollinearity is avoided
- Outliers are handled

Practical notes:
- For imbalanced data, monitor precision/recall/F1, not only accuracy
- Use `class_weight='balanced'` when class imbalance is high
- Tune threshold based on business cost of FP vs FN
- Use cross-validation for robust model selection

## Quick Recap

You now understand:
- Why logistic regression outputs probabilities (sigmoid)
- Why threshold tuning is important
- How to interpret coefficients and odds ratios
- How regularization controls overfitting
- Why ROC-AUC is useful beyond accuracy
- Key assumptions and real-world tips